from enum import Enum


class EnvVarKeys(Enum):
    """
    Enum of environment variables keys used by the application.
    """

    CRIANCA_DATASET_ORIGINAL_FILE_PATH_KEY = "CRIANCA_DATASET_ORIGINAL_FILE_PATH"
    ACHADO_ANORMAL_DATASET_ORIGINAL_FILE_PATH_KEY = "ACHADO_ANORMAL_DATASET_ORIGINAL_FILE_PATH"
    TIPO_MORBIDADE_DATASET_ORIGINAL_FILE_PATH_KEY = "TIPO_MORBIDADE_DATASET_ORIGINAL_FILE_PATH"
    PARTO_DATASET_ORIGINAL_FILE_PATH_KEY = "PARTO_DATASET_ORIGINAL_FILE_PATH"
    GESTACAO_DATASET_ORIGINAL_FILE_PATH_KEY = "GESTACAO_DATASET_ORIGINAL_FILE_PATH"
    MULHER_DATASET_ORIGINAL_FILE_PATH_KEY = "MULHER_DATASET_ORIGINAL_FILE_PATH"
    DADO_EVOLUTIVO_DATASET_ORIGINAL_FILE_PATH_KEY = "DADO_EVOLUTIVO_DATASET_ORIGINAL_FILE_PATH"
    UNIFIED_DATASET_PATH_KEY = "UNIFIED_DATASET_PATH"
    PRE_PROCESSED_DATASET_PATH_KEY = "PRE_PROCESSED_DATASET_PATH"
    DISTRIBUTION_DATASET_PATH_KEY = "DISTRIBUTION_DATASET_PATH"
    TELEGRAM_TOKEN_KEY_A = "TELEGRAM_TOKEN_A"
    TELEGRAM_CHAT_ID_KEY_A = "TELEGRAM_CHAT_ID_A"
    TELEGRAM_TOKEN_KEY_B = "TELEGRAM_TOKEN_B"
    TELEGRAM_CHAT_ID_KEY_B = "TELEGRAM_CHAT_ID_B"
    TELEGRAM_TOKEN_KEY_C = "TELEGRAM_TOKEN_C"
    TELEGRAM_CHAT_ID_KEY_C = "TELEGRAM_CHAT_ID_C"
    TELEGRAM_TOKEN_KEY_D = "TELEGRAM_TOKEN_D"
    TELEGRAM_CHAT_ID_KEY_D = "TELEGRAM_CHAT_ID_D"
    TELEGRAM_TOKEN_KEY_E = "TELEGRAM_TOKEN_E"
    TELEGRAM_CHAT_ID_KEY_E = "TELEGRAM_CHAT_ID_E"
    TELEGRAM_TOKEN_KEY_LOCAL = "TELEGRAM_TOKEN_LOCAL"
    TELEGRAM_CHAT_ID_KEY_LOCAL = "TELEGRAM_CHAT_ID_LOCAL"
    LOG_FILE_PATH_KEY = "LOG_FILE_PATH"
